import { useState, useEffect } from 'react'
import { useLocation } from 'wouter'
import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import { useAuth } from '@/contexts/AuthContext'
import { createBidSubmission, fetchTenderById, setFavorite, type Tender } from '@/lib/supabase'
import { toast } from 'sonner'
import { Heart } from 'lucide-react'

export default function TenderDetail({ params }: { params: { id: string } }) {
  const [tender, setTender] = useState<Tender | null>(null)
  const [loading, setLoading] = useState(true)
  const [isFavorite, setIsFavorite] = useState(false)
  const { profile } = useAuth()
  const [, navigate] = useLocation()

  useEffect(() => {
    const loadTender = async () => {
      setLoading(true)
      const data = await fetchTenderById(params.id)
      if (!data) {
        toast.error('Tender not found')
        navigate('/')
        return
      }
      setTender(data)
      if (profile) {
        const stored = typeof window !== 'undefined' ? JSON.parse(window.localStorage.getItem('gambids:favorites') || '{}') : {}
        setIsFavorite(Boolean(stored[profile.id]?.includes(params.id)))
      }
      setLoading(false)
    }
    loadTender()
  }, [params.id, profile])

  const handleToggleFavorite = async () => {
    if (!profile) {
      toast.error('Please sign in to save favorites')
      return
    }

    if (!tender) return

    try {
      await setFavorite(profile.id, tender.id, !isFavorite)
      setIsFavorite(!isFavorite)
      toast.success(isFavorite ? 'Removed from favorites' : 'Added to favorites')
    } catch {
      toast.error('Failed to update favorite')
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Spinner className="w-8 h-8" />
      </div>
    )
  }

  const handleSubmitApplication = async () => {
    if (!profile) {
      toast.error('Please sign in before submitting an application')
      navigate('/login')
      return
    }
    const rawAmount = window.prompt('Enter your bid amount in GMD')
    if (!rawAmount) return
    const amount = Number(rawAmount.replace(/,/g, ''))
    if (!Number.isFinite(amount) || amount <= 0) {
      toast.error('Enter a valid bid amount')
      return
    }
    await createBidSubmission(profile.id, tender!, amount)
    toast.success('Application submitted and added to My Submissions')
    navigate('/dashboard')
  }

  const handleDownloadDocuments = () => {
    const contents = `${tender?.title}\n${tender?.code}\n${tender?.org}\n\nDownload pack generated by GAM-BIDS.`
    const blob = new Blob([contents], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = `${tender?.code || 'tender'}-documents.txt`
    anchor.click()
    URL.revokeObjectURL(url)
    toast.success('Tender document pack downloaded')
  }

  if (!tender) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Tender not found</h1>
          <Button onClick={() => navigate('/')}>Back to home</Button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-ink border-b-4 border-laterite">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-laterite to-ochre flex items-center justify-center text-white font-bold text-sm">
              GB
            </div>
            <div>
              <div className="font-bold text-lg text-paper font-serif">GAM-BIDS</div>
              <div className="text-xs text-ochre font-semibold tracking-widest uppercase">
                Tender Details
              </div>
            </div>
          </div>
          <Button
            onClick={() => navigate('/')}
            variant="outline"
            className="border-paper text-paper hover:bg-white/10"
          >
            ← Back
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        {/* Title Section */}
        <div className="mb-8">
          <div className="flex items-start justify-between gap-4 mb-4">
            <div className="flex-1">
              <div className="text-xs text-muted font-mono mb-2">{tender.code}</div>
              <h1 className="text-4xl font-bold font-serif mb-4 leading-tight">
                {tender.title}
              </h1>
              <div className="flex gap-4 text-sm text-muted mb-6">
                <span>📍 {tender.region}</span>
                <span>🏛️ {tender.org}</span>
                <span>📅 Posted {tender.posted} days ago</span>
              </div>
            </div>
            <button
              onClick={handleToggleFavorite}
              className={`flex-shrink-0 p-3 rounded-lg transition ${
                isFavorite
                  ? 'bg-laterite/20 text-laterite'
                  : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
              }`}
            >
              <Heart className="w-6 h-6" fill={isFavorite ? 'currentColor' : 'none'} />
            </button>
          </div>

          {/* Deadline Stamp */}
          <div
            className={`inline-block px-6 py-3 border-2 rounded-full font-mono text-center ${
              tender.deadline <= 7
                ? 'border-laterite text-laterite bg-laterite/5'
                : 'border-river text-river bg-river/5'
            }`}
          >
            <div className="text-2xl font-bold">{tender.deadline}</div>
            <div className="text-xs font-semibold tracking-wider uppercase">
              days left
            </div>
          </div>
        </div>

        {/* Details Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <div className="bg-white border border-line rounded-lg p-6">
            <div className="text-xs text-muted font-semibold uppercase tracking-widest mb-2">
              Tender Type
            </div>
            <div className="text-lg font-semibold">{tender.type}</div>
          </div>

          <div className="bg-white border border-line rounded-lg p-6">
            <div className="text-xs text-muted font-semibold uppercase tracking-widest mb-2">
              Region
            </div>
            <div className="text-lg font-semibold">{tender.region}</div>
          </div>

          <div className="bg-white border border-line rounded-lg p-6">
            <div className="text-xs text-muted font-semibold uppercase tracking-widest mb-2">
              Organization
            </div>
            <div className="text-lg font-semibold">{tender.org}</div>
          </div>
        </div>

        {/* Description */}
        <div className="bg-white border border-line rounded-lg p-8 mb-12">
          <h2 className="text-2xl font-bold font-serif mb-4">Description</h2>
          <p className="text-muted leading-relaxed mb-6">
            This is a {tender.type.toLowerCase()} tender for {tender.org} in the {tender.region}. Interested bidders are invited to submit their proposals in accordance with the tender requirements and specifications.
          </p>

          <h3 className="text-lg font-semibold mb-3">Scope of Work</h3>
          <ul className="space-y-2 text-muted">
            <li>• Supply and delivery of goods/services as specified</li>
            <li>• Compliance with all government procurement regulations</li>
            <li>• Quality assurance and timely delivery</li>
            <li>• Adherence to technical specifications</li>
          </ul>
        </div>

        {/* Requirements */}
        <div className="bg-white border border-line rounded-lg p-8 mb-12">
          <h2 className="text-2xl font-bold font-serif mb-4">Requirements</h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-semibold mb-2">Eligibility</h3>
              <p className="text-muted">
                Bidders must be registered with the appropriate regulatory bodies and have a valid tax identification number.
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-2">Documentation</h3>
              <ul className="space-y-1 text-muted">
                <li>• Company registration certificate</li>
                <li>• Tax clearance certificate</li>
                <li>• Audited financial statements (last 2 years)</li>
                <li>• Technical proposal</li>
                <li>• Financial proposal</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2">Bid Security</h3>
              <p className="text-muted">
                A bid security of 2% of the estimated tender value is required.
              </p>
            </div>
          </div>
        </div>

        {/* Timeline */}
        <div className="bg-white border border-line rounded-lg p-8 mb-12">
          <h2 className="text-2xl font-bold font-serif mb-6">Timeline</h2>
          <div className="space-y-4">
            <div className="flex gap-4">
              <div className="w-2 h-2 rounded-full bg-river mt-2 flex-shrink-0"></div>
              <div>
                <div className="font-semibold">Tender Publication</div>
                <div className="text-sm text-muted">Today</div>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="w-2 h-2 rounded-full bg-river mt-2 flex-shrink-0"></div>
              <div>
                <div className="font-semibold">Bid Submission Deadline</div>
                <div className="text-sm text-muted">{tender.deadline} days from now</div>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="w-2 h-2 rounded-full bg-groundnut mt-2 flex-shrink-0"></div>
              <div>
                <div className="font-semibold">Bid Evaluation</div>
                <div className="text-sm text-muted">{tender.deadline + 7} days from now</div>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="w-2 h-2 rounded-full bg-groundnut mt-2 flex-shrink-0"></div>
              <div>
                <div className="font-semibold">Winner Announcement</div>
                <div className="text-sm text-muted">{tender.deadline + 14} days from now</div>
              </div>
            </div>
          </div>
        </div>

        {/* Contact & Application */}
        <div className="bg-gradient-to-br from-river/10 to-river/5 border border-river/20 rounded-lg p-8 mb-12">
          <h2 className="text-2xl font-bold font-serif mb-6">How to Apply</h2>
          <div className="space-y-4 mb-8">
            <div>
              <h3 className="font-semibold mb-2">Contact Information</h3>
              <div className="space-y-1 text-muted">
                <p><span className="font-semibold">Organization:</span> {tender.org}</p>
                <p><span className="font-semibold">Email:</span> procurement@{tender.org.toLowerCase().replace(/\s+/g, '')}.gm</p>
                <p><span className="font-semibold">Phone:</span> +220 (XXX) XXX-XXXX</p>
              </div>
            </div>
            <div>
              <h3 className="font-semibold mb-2">Submission Method</h3>
              <p className="text-muted">
                Submit sealed bids to the organization's procurement office. Bids must be submitted before the deadline.
              </p>
            </div>
          </div>

          <div className="flex gap-4">
            <Button onClick={handleDownloadDocuments} className="flex-1 bg-river hover:bg-river-dark text-white">
              Download Tender Documents
            </Button>
            <Button onClick={handleSubmitApplication} className="flex-1 bg-laterite hover:bg-laterite-dark text-white">
              Submit Application
            </Button>
          </div>
        </div>

        {/* Related Tenders */}
        <div>
          <h2 className="text-2xl font-bold font-serif mb-6">Related Tenders</h2>
          <Button onClick={() => navigate('/')} variant="outline" className="border-river text-river hover:bg-river/10">
            Browse more {tender.type.toLowerCase()} tenders in {tender.region} →
          </Button>
        </div>
      </main>
    </div>
  )
}
